[package]
name = "post-haste"
version = "0.1.0"
edition = "2024"

[dependencies]
const_env = "0.1.2"
embassy-executor = "0.7.0"
embassy-sync = "0.6.2"
embassy-time = "0.4.0"
portable-atomic = { version = "1.11.0", features = ["unsafe-assume-single-core"] }
